### ISSUE TITLE
can't install webcomponent Tester

### ISSUE THREAD

**Issue by davidigza** [Polymer/web-component-tester#190]
I've got this error on npm install -g web component tester

> web-component-tester@3.2.0 postinstall /usr/local/lib/node_modules/web-component-tester
> node scripts/postinstall.js

/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:56
				throw err;
				      ^
Error: EACCES, permission denied '/Users/davidiglesias/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:500:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:352:15)
    at Object.create.all.get (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "web-component-tester"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! web-component-tester@3.2.0 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-component-tester@3.2.0 postinstall script 'node scripts/postinstall.js'.
npm ERR! This is most likely a problem with the web-component-tester package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-component-tester
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/davidiglesias/Documents/Proyectos/cells-core/npm-debug.log

**Comment by jannakha** [comment]
hey! are you on a mac? Go to Disk Utility and do Repair Disk Permissions - then try to reinstall - that should fix it :-)

**Comment by j0hnsmith** [comment]
I also had this error with node v0.12.0 (on a mac), I tried Repair Disk Permissions but that didn't help. I installed node v0.10.40 but that didn't help either.

    Error: EACCES, permission denied '/Users/peter/.config/configstore/bower-github.yml'
    You don't have access to this file.

        at Object.fs.openSync (evalmachine.<anonymous>:439:18)
        at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
        at Object.create.all.get (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:34:29)
        at Object.Configstore (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:27:44)
        at readCachedConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:22:23)
        at defaultConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:11:24)
        at Object.<anonymous> (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/index.js:40:32)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)

    npm ERR! web-component-tester@3.3.0 postinstall: `node scripts/postinstall.js`
    npm ERR! Exit status 8
    npm ERR! 
    npm ERR! Failed at the web-component-tester@3.3.0 postinstall script.
    npm ERR! This is most likely a problem with the web-component-tester package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node scripts/postinstall.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls web-component-tester
    npm ERR! There is likely additional logging output above.
    npm ERR! System Darwin 14.3.0
    npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "web-component-tester"
    npm ERR! cwd /Users/peter/projects/kazoup/docker-appliance
    npm ERR! node -v v0.10.40
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

Here's the file

    $ ls -la /Users/peter/.config/configstore/bower-github.yml
    -rw-r--r--  1 peter  staff  3 14 Jul 15:50 /Users/peter/.config/configstore/bower-github.yml

**Comment by zwolfeintuit** [comment]
I'm having the same issue... were you able to find a solution? Thanks!

**Comment by markovuksanovic** [comment]
I'm running into this issue as well but on Linux machine. I'm trying to install this as root user and still doesn't work.

**Comment by juancferrer** [comment]
Same thing for me, on ubuntu.  Even setting those files to 777, and running with sudo doesn't fix the problem.  WTF

**Comment by jk3856** [comment]
Running into the same issue (using mac)

**Comment by fousheezy** [comment]
Running on OSX, also failed even after repairing disk permissions.

**Comment by nazar-pc** [comment]
Ended up installing locally in home directory: `npm install web-component-tester` and added bin directory to PATH, for this add to `~/.profile`:
```
# set PATH so it includes NPM's bin if it exists
if [ -d "$HOME/node_modules/.bin" ] ; then
    PATH="$HOME/node_modules/.bin:$PATH"
fi
```
And reboot.
P.S. For Ubuntu

**Comment by schafeld** [comment]
I got the same problem on Mac OS X. I tried the work-arounds suggested above (chmod / sudo / fixing disk permissions) – no success.

I can `npm install` locally (without `-g`), but calling the `wtc` file ends like this:

```
selenium-standalone installation finished
-----
Exception in thread "main"
java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncher : Unsupported major.minor version 51.0

 ...

Error: Another Selenium process is already running
```

There don't seem to be any other Selenium instances running, however. The "unsupported major minor" problem apparently hints at Java incompatibilities.

**Comment by TFarla** [comment]
@schafeld I have the same problem. Found a solution?

**Comment by mpruessmeier** [comment]
I have to ask for a solution too.

**Comment by schafeld** [comment]
Haven't found any solution yet.

Tried a 'clean' Polymer setup using Vagrant. After spending hours to get npm running inside Vagrant (lots of updates and some tweeking required), I seem to have at least a proper Polymer Startup Kit 1.1 installation within Vagrant. 
I.e. `gulp serve` works and `curl http://localhost:5000` displays what seems to be Polymer's initial page.
However `gulp test` throws "Error: No browsers configured to run" and I'm not sure how to find or configure a local browser for wct inside Vagrant. 

And then, of course, there would remain the problem to serve the pages to my Mac OS browser in order to actually see a page rendered...

**Comment by TFarla** [comment]
@schafeld I had no luck with vagrant either. After hitting "Error: No browsers configured to run". I installed firefox and a GUI for the box. 
It got the tests to run but they still failed regardless.

All in all, really not worth spending so many hours on.

**Comment by wbprice** [comment]
@schafeld I was running into the same error message as you:
```Exception in thread "main"
java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncher : Unsupported major.minor version 51.0```
And was able to resolve by installing a newer version of the JDK.  I used JDK 7, don't know if JDK 8 would also work.

**Comment by TFarla** [comment]
@wbprice Confirmed, upgrading the JDK fixed it for me. Thanks!

**Comment by schafeld** [comment]
@wbprice Thanks for confirming my suspicion about an outdated JDB being the cause of my troubles. The Polymer documentation actually says somewhere, that JDK 7 is required.

The thing is: I downloaded both versions of the JDK installer (v7 and v8) and neither is working on my Mac. Nothing happens after I press the 'Install' button. I couldn't find anything about this peculiar bug on the web.

**Comment by exavatar** [comment]
I am on a Mac, with Java 1.8.0_25, and I am seeing the 'don't have access' error.

**Comment by PaulRogers909** [comment]
Thanks for the JDK tip, I had issue's running protractor and found this article which fixed it for me on OSX.

**Comment by hugomatic** [comment]
Same problem on Ubuntu 14.04.3 LTS, npm 2.14.4 node v4.1.1

**Comment by akc42** [comment]
I have the same problem on Mac OSX 10.11

I have just installed nodejs 4.2.1 and tried to install web-component-tester

sudo npm install -g web-component-tester

This is the last (and relevant) bit of the output.  What seems strange is that I should be running as root with the sudo, yet its an access error into something in my own home directory

usr/local/bin/wct -> /usr/local/lib/node_modules/web-component-tester/bin/wct
/usr/local/bin/wct-st -> /usr/local/lib/node_modules/web-component-tester/bin/wct-st

> web-component-tester@3.3.26 postinstall /usr/local/lib/node_modules/web-component-tester
> node scripts/postinstall.js

/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/mkdirp/index.js:89
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/Users/alan/.config/configstore'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at Function.sync (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/mkdirp/index.js:70:13)
    at Object.create.all.get (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:41:13)
    at Object.Configstore (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/web-component-tester/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "web-component-tester"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! web-component-tester@3.3.26 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-component-tester@3.3.26 postinstall script 'node scripts/postinstall.js'.
npm ERR! This is most likely a problem with the web-component-tester package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-component-tester
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alan/Documents/pasv5/npm-debug.log

**Comment by CICCIOSGAMINO** [comment]
Same problem on Ubuntu 14.04.3 LTS, npm 2.14.2 node v4.0 ! I can't get what's wrong !
