### ISSUE TITLE
I can't get Iceweasel to work

### ISSUE THREAD

**Issue by akc42** [Polymer/web-component-tester#290]
I was under the impression that Iceweasel (Debian branded) was firefox.  But my attempts to use it with wct are failing.

I have a project which is getting larger all the time, but I have yet to really get going on the client testing side.  I am trying to rectify that.  I have set up some fairly basic tests which do very little than establish a fixture and call describe with a beforeEach in them.  No real test yet.  On chrome these tests run in milliseconds.  But if I forece wct to use firefox (I am not configuring firefox in wct.conf.json because of this problem) with the command line switch `--browsers=firefox` then the whole thing starts up to get as far as outputting the following on the terminal and opening a blank browser window

```
alan@kanga:~/dev/pasv5[no-fire-for-grid]$ wct --browsers=firefox
The --browsers flag/option is deprecated. Please use --local and --sauce instead, or configure via plugins.[local|sauce].browsers.
Installing and starting Selenium server for local browsers
Selenium server running on port 33463
Web server running on port 2000 and serving from /home/alan/dev/pasv5

firefox 44 () 
```
And then hangs for a while (45 seconds to within a couple of seconds either way) and then spews out in red on the terminal a load of stuff like below. (This is only some of it)

```
Tests failed: {"sessionId":null,"status":13,"state":"unhandled error","value":{"message":"Unable to connect to host localhost on port 7055 after 45000 ms. Firefox console output:\nte\":1455790387000,\"updateDate\":1455790387000,\"applyBackgroundUpdates\":1,\"bootstrap\":false,\"size\":8235030,\"sourceURI\":null,\"releaseNotesURI\":null,\"softDisabled\":false,\"foreignInstall\":true,\"hasBinaryComponents\":true,\"strictCompatibility\":false,\"locales\":[],\"targetApplications\":[{\"id\":\"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}\",\"minVersion\":\"3.0\",\"maxVersion\":\"66.*\"}],\"targetPlatforms\":[{\"os\":\"Darwin\",\"abi\":null},{\"os\":\"SunOS\",\"abi\":null},{\"os\":\"FreeBSD\",\"abi\":null},{\"os\":\"OpenBSD\",\"abi\":null},{\"os\":\"WINNT\",\"abi\":\"x86-msvc\"},{\"os\":\"Linux\",\"abi\":null}],\"multiprocessCompatible\":false,\"signedState\":0}\n1455790388182\taddons.xpi\tDEBUG\tUpdating XPIState for {\"id\":\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"syncGUID\":\"7JWml6cb6FAR\",\"location\":\"app-global\",\"version\":\"44.0\",\"type\":\"theme\",\"internalName\":\"classic/1.0\",\"updateURL\":null,\"updateKey\":null,\"optionsURL\":null,\"optionsType\":null,\"aboutURL\":null,\"icons\":{\"32\":\"icon.png\",\"48\":\"icon.png\"},\"iconURL\":null,\"icon64URL\":null,\"defaultLocale\":{\"name\":\"Default\",\"description\":\"The default theme.\",\"creator\":\"Mozilla\",\"homepageURL\":null,\"contributors\":[\"Mozilla Contributors\"]},\"visible\":true,\"active\":true,\"userDisabled\":false,\"appDisabled\":false,\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"installDate\":1455713905000,\"updateDate\":1455713905000,\"applyBackgroundUpdates\":1,\"skinnable\":true,\"size\":5022,\"sourceURI\":null,\"releaseNotesURI\":null,\"softDisabled\":false,\"foreignInstall\":false,\"hasBinaryComponents\":false,\"strictCompatibility\":true,\"locales\":[],\"targetApplications\":[{\"id\":\"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}\",\"minVersion\":\"44.0\",\"maxVersion\":\"44.0\"}],\"targetPlatforms\":[]}\n1455790388182\taddons.xpi\tDEBUG\tgetModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}\n1455790388183\tDeferredSave.extensions.json\tDEBUG\tSave changes\n1455790388183\taddons.xpi\tDEBUG\tUpdating database with changes to installed add-ons\n1455790388183\taddons.xpi-utils\tDEBUG\tUpdating add-on states\n1455790388183\taddons.xpi-utils\tDEBUG\tWriting add-ons list\n1455790388185\taddons.manager\tDEBUG\tRegistering shutdown blocker for XPIProvider\n1455790388186\taddons.manager\tDEBUG\tProvider finished startup: XPIProvider\n1455790388186\taddons.manager\tDEBUG\tStarting provider: LightweightThemeManager\n1455790388186\taddons.manager\tDEBUG\tRegistering shutdown blocker for LightweightThemeManager\n1455790388186\taddons.manager\tDEBUG\tProvider finished startup: LightweightThemeManager\n1455790388186\taddons.manager\tDEBUG\tStarting provider: GMPProvider\n1455790388191\taddons.manager\tDEBUG\tRegistering shutdown blocker for GMPProvider\n1455790388191\taddons.manager\tDEBUG\tProvider finished startup: GMPProvider\n1455790388191\taddons.manager\tDEBUG\tStarting provider: PluginProvider\n1455790388191\taddons.manager\tDEBUG\tRegistering shutdown blocker for PluginProvider\n1455790388191\taddons.manager\tDEBUG\tProvider finished startup: PluginProvider\n1455790388192\taddons.manager\tDEBUG\tCompleted startup sequence\n1455790388357\taddons.manager\tDEBUG\tStarting provider: <unnamed-provider>\n1455790388357\taddons.manager\tDEBUG\tRegistering shutdown blocker for <unnamed-provider>\n1455790388357\taddons.manager\tDEBUG\tProvider finished startup: <unnamed-provider>\n1455790388417\tDeferredSave.extensions.json\tDEBUG\tStarting write\n1455790388486\taddons.repository\tDEBUG\tNo addons.json found.\n1455790388487\tDeferredSave.addons.json\tDEBUG\tSave changes\n1455790388489\tDeferredSave.addons.json\tDEBUG\tStarting timer\n1455790388500\taddons.manager\tDEBUG\tStarting provider: PreviousExperimentProvider\n1455790388500\taddons.manager\tDEBUG\tRegistering shutdown blocker for PreviousExperimentProvider\n1455790388500\taddons.manager\tDEBUG\tProvider finished startup: PreviousExperimentProvider\n1455790388502\tDeferredSave.extensions.json\tDEBUG\tWrite succeeded\n1455790388502\taddons.xpi-utils\tDEBUG\tXPI Database saved, setting schema version preference to 17\n1455790388563\tDeferredSave.addons.json\tDEBUG\tStarting write\n1455790388570\tDeferredSave.addons.json\tDEBUG\tWrite succeeded\nJavaScript error: resource://gre/modules/SafeBrowsing.jsm, line 83: TypeError: provider is undefined\n","suppressed":[],"localizedMessage":"Unable to connect to host localhost on port 7055 after 45000 ms. Firefox console output:\nte\":1455790387000,\"updateDate\":1455790387000,\"applyBackgroundUpdates\":1,\"bootstrap\":false,\"size\":8235030,\"sourceURI\":null,\"releaseNotesURI\":null,\"softDisabled\":false,\"foreignInstall\":true,\"hasBinaryComponents\":true,\"strictCompatibility\":false,\"locales\":[],\"targetApplications\":[{\"id\":\"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}\",\"minVersion\":\"3.0\",\"maxVersion\":\"66.*\"}],\"targetPlatforms\":[{\"os\":\"Darwin\",\"abi\":null},{\"os\":\"SunOS\",\"abi\":null},{\"os\":\"FreeBSD\",\"abi\":null},{\"os\":\"OpenBSD\",\"abi\":null},{\"os\":\"WINNT\",\"abi\":\"x86-msvc\"},{\"os\":\"Linux\",\"abi\":null}],\"multiprocessCompatible\":false,\"signedState\":0}\n1455790388182\taddons.xpi\tDEBUG\tUpdating XPIState for {\"id\":\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"syncGUID\":\"7JWml6cb6FAR\",\"location\":\"app-global\",\"version\":\"44.0\",\"type\":\"theme\",\"internalName\":\"classic/1.0\",\"updateURL\":null,\"updateKey\":null,\"optionsURL\":null,\"optionsType\":null,\"aboutURL\":null,\"icons\":{\"32\":\"icon.png\",\"48\":\"icon.png\"},\"iconURL\":null,\"icon64URL\":null,\"defaultLocale\":{\"name\":\"Default\",\"description\":\"The default theme.\",\"creator\":\"Mozilla\",\"homepageURL\":null,\"contributors\":[\"Mozilla Contributors\"]},\"visible\":true,\"active\":true,\"userDisabled\":false,\"appDisabled\":false,\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"installDate\":1455713905000,\"updateDate\":1455713905000,\"applyBackgroundUpdates\":1,\"skinnable\":true,\"size\":5022,\"sourceURI\":null,\"releaseNotesURI\":null,\"softDisabled\":false,\"foreignInstall\":false,\"hasBinaryComponents\":false,\"strictCompatibility\":true,\"locales\":[],\"targetApplications\":[{\"id\":\"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}\",\"minVersion\":\"44.0\",\"maxVersion\":\"44.0\"}],\"targetPlatforms\":[]}\n1455790388182\taddons.xpi\tDEBUG\tgetModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}\n1455790388183\tDeferredSave.extensions.json\tDEBUG\tSave changes\n1455790388183\taddons.xpi\tDEBUG\tUpdating database with changes to installed add-ons\n1455790388183\taddons.xpi-utils\tDEBUG\tUpdating add-on states\n1455790388183\taddons.xpi-utils\tDEBUG\tWriting add-ons list\n1455790388185\taddons.manager\tDEBUG\tRegistering shutdown blocker for XPIProvider\n1455790388186\taddons.manager\tDEBUG\tProvider finished startup: XPIProvider\n1455790388186\taddons.manager\tDEBUG\tStarting provider: LightweightThemeManager\n1455790388186\taddons.manager\tDEBUG\tRegistering shutdown blocker for LightweightThemeManager\n1455790388186\taddons.manager\tDEBUG\tProvider finished startup: LightweightThemeManager\n1455790388186\taddons.manager\tDEBUG\tStarting provider: GMPProvider\n1455790388191\taddons.manager\tDEBUG\tRegistering shutdown blocker for GMPProvider\n1455790388191\taddons.manager\tDEBUG\tProvider finished startup: GMPProvider\n1455790388191\taddons.manager\tDEBUG\tStarting provider: PluginProvider\n1455790388191\taddons.manager\tDEBUG\tRegistering shutdown blocker for PluginProvider\n1455790388191\taddons.manager\tDEBUG\tProvider finished startup: PluginProvider\n1455790388192\taddons.manager\tDEBUG\tCompleted startup sequence\n1455790388357\taddons.manager\tDEBUG\tStarting provider: <unnamed-provider>\n1455790388357\taddons.manager\tDEBUG\tRegistering shutdown blocker for <unnamed-provider>\n1455790388357\taddons.manager\tDEBUG\tProvider finished startup: <unnamed-provider>\n1455790388417\tDeferredSave.extensions.json\tDEBUG\tStarting write\n1455790388486\taddons.repository\tDEBUG\tNo addons.json found.\n1455790388487\tDeferredSave.addons.json\tDEBUG\tSave changes\n1455790388489\tDeferredSave.addons.json\tDEBUG\tStarting timer\n1455790388500\taddons.manager\tDEBUG\tStarting provider: PreviousExperimentProvider\n1455790388500\taddons.manager\tDEBUG\tRegistering shutdown blocker for PreviousExperimentProvider\n1455790388500\taddons.manager\tDEBUG\tProvider finished startup: PreviousExperimentProvider\n1455790388502\tDeferredSave.extensions.json\tDEBUG\tWrite succeeded\n1455790388502\taddons.xpi-utils\tDEBUG\tXPI Database saved, setting schema version preference to 17\n1455790388563\tDeferredSave.addons.json\tDEBUG\tStarting write\n1455790388570\tDeferredSave.addons.json\tDEBUG\tWrite succeeded\nJavaScript error: resource://gre/modules/SafeBrowsing.jsm, line 83: TypeError: provider is undefined\n","cause":null,"class":"org.openqa.selenium.firefox.NotConnectedException","hCode":786507085,"stackTrace":[{"fileName":"NewProfileExtensionConnection.java","class":"java.lang.StackTraceElement","lineNumber":122,"className":"org.openqa.selenium.firefox.internal.NewProfileExtensionConnection","nativeMethod":false,"methodName":"start","hCode":-527404734},{"fileName":"FirefoxDriver.java","class":"java.lang.StackTraceElement","lineNumber":276,"className":"org.openqa.selenium.firefox.FirefoxDriver","nativeMethod":false,"methodName":"startClient","hCode":-396788052},{"fileName":"RemoteWebDriver.java","class":"java.lang.StackTraceElement","lineNumber":116,"className":"org.openqa.selenium.remote.RemoteWebDriver","nativeMethod":false,"methodName":"<init>","hCode":2001602296},{"fileName":"FirefoxDriver.java","class":"java.lang.StackTraceElement","lineNumber":223,"className":"org.openqa.selenium.firefox.FirefoxDriver","nativeMethod":false,"methodName":"<init>","hCode":2005391580},{"fileName":"FirefoxDriver.java","class":"java.lang.StackTraceElement","lineNumber":216,"className":"org.openqa.selenium.firefox.FirefoxDriver","nativeMethod":false,"methodName":"<init>","hCode":2005391573},{"fileName":"FirefoxDriver.java","class":"java.lang.StackTraceElement","lineNumber":134,"className":"org.openqa.selenium.firefox.FirefoxDriver","nativeMethod":false,"methodName":"<init>","hCode":2005391491},{"fileName":"NativeConstructorAccessorImpl.java","class":"java.lang.StackTraceElement","lineNumber":-2,"className":"sun.reflect.NativeConstructorAccessorImpl","nativeMethod":true,"methodName":"newInstance0","hCode":-917798116},{"fileName":"NativeConstructorAccessorImpl.java","class":"java.lang.StackTraceElement","lineNumber":57,"className":"sun.reflect.NativeConstructorAccessorImpl","nativeMethod":false,"methodName":"newInstance","hCode":-1864225103},{"fileName":"DelegatingConstructorAccessorImpl.java","class":"java.lang.StackTraceElement","lineNumber":45,"className":"sun.reflect.DelegatingConstructorAccessorImpl","nativeMethod":false,"methodName":"newInstance","hCode":-2122307259},{"fileName":"Constructor.java","class":"java.lang.StackTraceElement","lineNumber":526,"className":"java.lang.reflect.Constructor","nativeMethod":false,"methodName":"newInstance","hCode":-1319859816},{"fileName":"DefaultDriverProvider.java","class":"java.lang.StackTraceElement","lineNumber":103,"className":"org.openqa.selenium.remote.server.DefaultDriverProvider","nativeMethod":false,"methodName":"callConstructor","hCode":-2096353668},{"fileName":"DefaultDriverProvider.java","class":"java.lang.StackTraceElement","lineNumber":97,"className":"org.openqa.selenium.remote.server.DefaultDriverProvider","nativeMethod":false,"methodName":"newInstance","hCode":1201680335},{"fileName":"DefaultDriverFactory.java","class":"java.lang.StackTraceElement","lineNumber":60,"className":"org.openqa.selenium.remote.server.DefaultDriverFactory","nativeMethod":false,"methodName":"newInstance","hCode":-1365021416},{"fileName":"DefaultSession.java","class":"java.lang.StackTraceElement","lineNumber":222,"className":"org.openqa.selenium.remote.server.DefaultSession$BrowserCreator","nativeMethod":false,"methodName":"call","hCode":2056168471},{"fileName":"DefaultSession.java","class":"java.lang.StackTraceElement","lineNumber":1,"className":"org.openqa.selenium.remote.server.DefaultSession$BrowserCreator","nativeMethod":false,"methodName":"call","hCode":2056168250},{"fileName":"FutureTask.java","class":"java.lang.StackTraceElement","lineNumber":262,"className":"java.util.concurrent.FutureTask","nativeMethod":false,"methodName":"run","hCode":-820313558},{"fileName":"DefaultSession.java","class":"java.lang.StackTraceElement","lineNumber":176,"className":"org.openqa.selenium.remote.server.DefaultSession$1","nativeMethod":false,"methodName":"run","hCode":-255143467},{"fileName":"ThreadPoolExecutor.java","class":"java.lang.StackTraceElement","lineNumber":1145,"className":"java.util.concurrent.ThreadPoolExecutor","nativeMethod":false,"methodName":"runWorker","hCode":-1285150181},{"fileName":"ThreadPoolExecutor.java","class":"java.lang.StackTraceElement","lineNumber":615,"className":"java.util.concurrent.ThreadPoolExecutor$Worker","nativeMethod":false,"methodName":"run","hCode":-242190647},{"fileName":"Thread.java","class":"java.lang.StackTraceElement","lineNumber":745,"className":"java.lang.Thread","nativeMethod":false,"methodName":"run","hCode":-82946320}],"screen":null},"class":"org.openqa.selenium.remote.Response","hCode":2006996402}
```

I am running a Debian system with open-jdk-7-jre installed.

Is there a simple cure for this, or a known bug, or am I stuck with only testing locally with Chrome?

**Comment by uwolfer** [comment]
The following workaround fixed this issue in my setup: https://github.com/Polymer/web-component-tester/issues/248#issuecomment-165189016

**Comment by justinfagnani** [comment]
That's good. Are you using WCT 4 though? Seems like this should be fixed.

**Comment by uwolfer** [comment]
@justinfagnani: Just tried again and I still can reproduce it when I revert these changes in my hosts file. Using web-component-tester#4.2.1.

**Comment by justinfagnani** [comment]
Ouch. I really have to bring myself up to speed on Selenium and this issue. I wonder if upgrading to Selenium 2.52 would help...

**Comment by uwolfer** [comment]
@justinfagnani: Just tried with 2.52 and it still does not work.

I have verified that I'm running the correct selenium version:

    $ java -jar node_modules/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/2.52.0-server.jar -Dwebdriver.chrome.driver=node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.21-x64-chromedriver -port 35768

**Comment by akc42** [comment]
just seen @uwolfer 's reference to #248.  My /etc/hosts file is fairly simple with ...
```
127.0.0.1	localhost
127.0.1.1	kanga.home	kanga
```

As the only two entries.

Haven't had time to try anything yet, probably later this week

**Comment by kito99** [comment]
FWIW, I'm getting the same problem with Mac OS X Yosemite and Firefox 45.01. Chrome and Safari run just fine (after installing the Safari extension for webdriver). Using wct 4.2.1.

**Comment by kito99** [comment]
I can also verify that downgrading to Firefox 41 fixes this issue (clearly not a long-term solution...)

**Comment by NicolasRannou** [comment]
Got same error with recent browsers...:
```
safari 10.0              Tests passed
chrome 51                Tests passed
chrome 54                Tests failed: {"state":"unhandled error","sessionId":null,"hCode":1558994120,"value":{"localizedMessage":"Connection refused","cause":null,"stackTrace":[{"fileName":"PlainSocketImpl.java","nativeMethod":true,"methodName":"socketConnect","className":"java.net.PlainSocketImpl","hCode":1566792002,"lineNumber":-2,"class":"java.lang.StackTraceElement"},{"fileName":"AbstractPlainSocketImpl.java","nativeMethod":false,"methodName":"doConnect","className":"java.net.AbstractPlainSocketImpl","hCode":495250501,"lineNumber":345,"class":"java.lang.StackTraceElement"},{"fileName":"AbstractPlainSocketImpl.java

...

chrome 54 (error)                       chrome 51 (1/0/0)                       firefox 47 (error)                    
safari 10.0 (1/0/0)
```

On macOS Sierra -
